# Generated by Django 4.1.3 on 2022-11-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('pros', models.TextField(max_length=250)),
                ('cons', models.TextField(max_length=250)),
            ],
        ),
    ]
