# Generated by Django 4.1.3 on 2022-11-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gear_alter_maintenance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='picture',
            field=models.CharField(default='https://www.rei.com/media/86715e00-01f8-4fb6-aacf-8a30add086c0?size=784x588', max_length=200),
        ),
    ]
