# Generated by Django 4.1.3 on 2022-11-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_gear_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='Item',
            new_name='item',
        ),
    ]
