# Generated by Django 4.1.3 on 2022-11-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_item_gear_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='pros',
        ),
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(choices=[('E', 'E-Bike'), ('R', 'Road Bike'), ('G', 'Gravel Bike'), ('H', 'Hybrid Bike'), ('M', 'Mountain Bike'), ('T', 'Touring Bike'), ('O', 'Other')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='gear',
            name='picture',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
