# Generated by Django 4.1.3 on 2022-11-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_bike_cons_remove_bike_pros_alter_bike_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
