# Generated by Django 4.1.3 on 2022-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_bike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='details',
            field=models.CharField(default='gear details here', max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(choices=[('E', 'E-Bike'), ('R', 'Road Bike'), ('G', 'Gravel Bike'), ('H', 'Hybrid Bike'), ('M', 'Mountain Bike'), ('T', 'Touring Bike'), ('O', 'Unique Bike')], default='E', max_length=1),
        ),
    ]
