# Generated by Django 4.1.3 on 2022-11-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_gear_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='details',
        ),
    ]
