# Generated by Django 4.1.3 on 2022-11-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_gear_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='details',
            field=models.CharField(default='write details here', max_length=200),
        ),
    ]